
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "2222:22"
      - "8081:80" 
  node2:
    build: .
    container_name: node2
    ports:
      - "2223:22"
      - "8082:80"
